Repository adobe/spectrum-web-components, pull requests merged in 2024-05, with the labels that each got.

#4417 fix(number-field): handles values greater than 1000
  packages/number-field/src/NumberField.ts
  packages/number-field/test/number-field.test.ts
Labels: bug, Component: Number Field

#4446 fix: revert netlify back to v15
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Tooling

#4241 fix(styles,theme): add S2 tokens and theme
  .circleci/config.yml
  package.json
  packages/action-bar/src/ActionBar.ts
  packages/overlay/src/slottable-request-directive.ts
  projects/documentation/content/guides/generating-components.md
  projects/documentation/src/components/layout.ts
  projects/story-decorator/src/StoryDecorator.ts
  projects/vrt-quick-link/404.html
  scripts/generate-tokens-wrapper.js
  scripts/generate-tokens.js
  tasks/build-preview-urls-comment.js
  test/visual/review.js
  tools/base/src/version.js
  tools/styles/exports.json
  tools/styles/package.json
  tools/styles/tokens-v2/dark-vars.css
  tools/styles/tokens-v2/global-vars.css
  tools/styles/tokens-v2/large-vars.css
  tools/styles/tokens-v2/light-vars.css
  tools/styles/tokens-v2/medium-vars.css
  tools/styles/tokens-v2/spectrum/custom-dark-vars.css
  tools/styles/tokens-v2/spectrum/custom-darkest-vars.css
  tools/styles/tokens-v2/spectrum/custom-large-vars.css
  tools/styles/tokens-v2/spectrum/custom-light-vars.css
  tools/styles/tokens-v2/spectrum/custom-medium-vars.css
  tools/styles/tokens-v2/spectrum/custom-vars.css
  tools/styles/tokens-v2/spectrum/global-vars.css
  tools/theme/exports.json
  tools/theme/package.json
  tools/theme/spectrum-two/scale-large-core-tokens.ts
  tools/theme/spectrum-two/scale-medium-core-tokens.ts
  tools/theme/spectrum-two/theme-dark-core-tokens.ts
  tools/theme/spectrum-two/theme-light-core-tokens.ts
  tools/theme/src/Theme.ts
  tools/theme/src/spectrum-two/core-tokens.ts
  tools/theme/src/spectrum-two/core.ts
  tools/theme/src/spectrum-two/scale-large-core-tokens.css
  tools/theme/src/spectrum-two/scale-medium-core-tokens.css
  tools/theme/src/spectrum-two/theme-core-tokens.css
  tools/theme/src/spectrum-two/theme-dark-core-tokens.css
  tools/theme/src/spectrum-two/theme-light-core-tokens.css
  tools/theme/src/spectrum-two/theme.css
  tools/theme/src/spectrum-two/themes-core-tokens.ts
  tools/theme/test/theme-devmode.test.ts
  tools/theme/tsconfig.json
  web-test-runner.utils.js
  yarn.lock
Labels: S2

#4448 add more tests to improve code coverage across the library
  packages/button/test/button.test.ts
  packages/progress-circle/test/progress-circle.test.ts
  packages/thumbnail/test/thumbnail.test.ts
  packages/underlay/test/underlay.test.ts
Labels: Testing

#4455 fix(coachmark,overlay): adjust imports of overlay and coachmark
  packages/coachmark/src/Coachmark.ts
  packages/overlay/src/overlay-trigger-directive.ts
Labels: bug, dependencies

#4507 fix: duplicate code to empty global-vars before generating
  scripts/generate-tokens-wrapper.js
Labels: bug

#4508 fix(number-field): updated number field to respect all locales
  packages/number-field/src/NumberField.ts
  packages/number-field/test/number-field.test.ts
Labels: bug, Component: Number Field

#4512 chore(docs): updated demo examples nunjucks template to include all types of args
  projects/documentation/content/_includes/partials/demo.njk
  projects/documentation/src/components.ts
Labels: Documentation

#4514 chore(tabs): update overflow icon color
  packages/tabs/src/tabs-overflow.css
Labels: Component: Tabs
