Repository adobe/spectrum-web-components, pull requests merged in 2024-10, with the labels that each got.

#4747 chore: s2 icons
  .github/workflows/coveralls.yml
  .github/workflows/pr-update.yml
  .github/workflows/publish.yml
  .github/workflows/smoke.yml
  .github/workflows/test.yml
  .gitignore
  README.md
  package.json
  packages/icon/src/IconBase.ts
  packages/icon/src/spectrum-icon.css
  packages/icons-ui/.gitignore
  packages/icons-ui/bin/build.js
  packages/icons-ui/package.json
  packages/icons-ui/tsconfig.json
  packages/icons-workflow/.gitignore
  packages/icons-workflow/bin/build.js
  packages/icons-workflow/package.json
  packages/icons-workflow/src/DefaultIcon.ts
  packages/icons-workflow/tsconfig.json
  scripts/icons-sync.json
  tools/theme/README.md
  tools/theme/src/Theme.ts
  tools/theme/src/theme-interfaces.ts
  yarn.lock
Labels: Breaking, Component: Icon, S2

#4722 fix(tabs): scroll exceeding tabs limit
  packages/tabs/src/Tabs.ts
  packages/tabs/src/TabsOverflow.ts
  packages/tabs/test/tabs-overflow.test.ts
Labels: bug, Component: Tabs, iOS

#4772 chore: remove 'variant' and 'static' attributes from coach indicator
  packages/coachmark/coach-indicator.md
  packages/coachmark/src/CoachIndicator.ts
  packages/coachmark/stories/coach-indicator-static.stories.ts
  packages/coachmark/test/coach-indicator.test.ts
Labels: 1.0.0, Breaking

#4729 chore: remove split-button component
  INVENTORY.md
  packages/.eslintrc.json
  packages/menu/menu-item.md
  packages/split-button/CHANGELOG.md
  packages/split-button/README.md
  packages/split-button/exports.json
  packages/split-button/package.json
  packages/split-button/sp-split-button.ts
  packages/split-button/src/SplitButton.ts
  packages/split-button/src/index.ts
  packages/split-button/src/spectrum-config.js
  packages/split-button/src/spectrum-split-button.css
  packages/split-button/src/split-button.css
  packages/split-button/stories/index.ts
  packages/split-button/stories/split-button-accent-field.stories.ts
  packages/split-button/stories/split-button-accent-more.stories.ts
  packages/split-button/stories/split-button-primary-field.stories.ts
  packages/split-button/stories/split-button-primary-more.stories.ts
  packages/split-button/stories/split-button-secondary-field.stories.ts
  packages/split-button/stories/split-button-secondary-more.stories.ts
  packages/split-button/sync/sp-split-button.ts
  packages/split-button/test/benchmark/basic-test.ts
  packages/split-button/test/index.ts
  packages/split-button/test/split-button-memory.test.ts
  packages/split-button/test/split-button-sync.test.ts
  packages/split-button/test/split-button.test.ts
  packages/split-button/tsconfig.json
  tools/.eslintrc.json
  tools/base/test/define-element.test.ts
  tools/bundle/elements.ts
  tools/bundle/src/index.ts
  tools/bundle/tsconfig.json
  tsconfig-all.json
  tsconfig-react-wrapper.json
  web-test-runner.config.js
Labels: 1.0.0, Breaking

#4723 chore: remove banner component
  INVENTORY.md
  packages/banner/CHANGELOG.md
  packages/banner/README.md
  packages/banner/exports.json
  packages/banner/package.json
  packages/banner/sp-banner.ts
  packages/banner/src/Banner.ts
  packages/banner/src/banner.css
  packages/banner/src/index.ts
  packages/banner/src/spectrum-banner.css
  packages/banner/src/spectrum-config.js
  packages/banner/stories/banner.stories.ts
  packages/banner/test/banner-memory.test.ts
  packages/banner/test/banner.test.ts
  packages/banner/test/benchmark/test-basic.ts
  packages/banner/tsconfig.json
  tools/base/test/define-element.test.ts
  tools/bundle/elements.ts
  tools/bundle/src/index.ts
  tools/bundle/tsconfig.json
  tsconfig-all.json
  tsconfig-react-wrapper.json
  yarn.lock
Labels: 1.0.0, Breaking

#4742 chore: remove deprecated badge `fixed` values
  packages/badge/src/Badge.ts
  packages/badge/src/badge.css
  packages/badge/test/badge.test.ts
Labels: 1.0.0, Breaking

#4761 chore: remove sp-quick-actions
  INVENTORY.md
  packages/card/src/Card.ts
  packages/card/src/card.css
  packages/card/src/spectrum-card.css
  packages/card/src/spectrum-config.js
  packages/card/stories/card.stories.ts
  packages/coachmark/src/Coachmark.ts
  packages/quick-actions/CHANGELOG.md
  packages/quick-actions/README.md
  packages/quick-actions/exports.json
  packages/quick-actions/package.json
  packages/quick-actions/sp-quick-actions.ts
  packages/quick-actions/src/QuickActions.ts
  packages/quick-actions/src/index.ts
  packages/quick-actions/src/quick-actions.css
  packages/quick-actions/src/spectrum-config.js
  packages/quick-actions/src/spectrum-quick-actions.css
  packages/quick-actions/stories/quick-actions.stories.ts
  packages/quick-actions/test/benchmark/basic-test.ts
  packages/quick-actions/test/quick-actions.test.ts
  packages/quick-actions/tsconfig.json
  projects/documentation/scripts/gather-spectrum-urls.js
  tools/base/test/define-element.test.ts
  tools/bundle/elements.ts
  tools/bundle/src/index.ts
  tools/bundle/tsconfig.json
  tsconfig-all.json
  tsconfig-react-wrapper.json
  yarn.lock
Labels: 1.0.0, Breaking

#4751 chore: remove popover's dialog property
  packages/popover/src/Popover.ts
  packages/popover/src/spectrum-config.js
  packages/popover/stories/popover.stories.ts
  packages/popover/test/benchmark/test-basic.ts
  packages/popover/test/popover.test.ts
Labels: 1.0.0, Breaking

#4760 chore: remove thumbnail deprecated sizes
  packages/thumbnail/src/Thumbnail.ts
  packages/thumbnail/test/thumbnail.test.ts
Labels: 1.0.0, Breaking

#4750 chore: remove progress-circle overBackground property
  packages/progress-circle/README.md
  packages/progress-circle/src/ProgressCircle.ts
  packages/progress-circle/test/progress-circle.test.ts
Labels: 1.0.0, Breaking

#4765 chore: remove 'theme' attribute from sp-theme
  .circleci/config.yml
  packages/dialog/test/dialog-base.test.ts
  packages/dialog/test/dialog-wrapper.test.ts
  packages/overlay/test/overlay-element.test.ts
  packages/overlay/test/overlay-trigger-hover.test.ts
  packages/overlay/test/overlay-v1.test.ts
  packages/overlay/test/overlay.test.ts
  packages/picker-button/README.md
  packages/table/test/helpers.ts
  packages/table/test/virtualized-table-selects.test.ts
  packages/tray/test/tray.test.ts
  projects/documentation/content/using-swc-react.md
  projects/documentation/content/what-is-a-theme.md
  tools/theme/README.md
  tools/theme/core-tokens.ts
  tools/theme/src/Theme.ts
  tools/theme/src/express/core-tokens.ts
  tools/theme/src/theme-interfaces.ts
  tools/theme/test/theme-devmode.test.ts
  tools/theme/test/theme-lazy.test.ts
  tools/theme/test/themes.test.ts
  web-test-runner.utils.js
Labels: 1.0.0, Breaking

#4776 feat: add 1.0.0 migration guide
  projects/documentation/content/migrations/2024-10-31 (1.0.0).md
Labels: 1.0.0, Documentation

#4833 fix: thumbnail border opacity
  packages/thumbnail/package.json
  packages/thumbnail/src/spectrum-thumbnail.css
  yarn.lock
Labels: Component: Thumbnail
