Repository adobe/spectrum-web-components, pull requests merged in 2025-08, with the labels that each got.

#5664 chore(alert-banner): refactor AlertBanner to extend AlertBannerBase
  packages/alert-banner/src/AlertBanner.base.ts
  packages/alert-banner/src/AlertBanner.ts
Labels: ready-for-review

#5672 fix(picker): Escape key behavior in modal overlays containing picker components
  .changeset/fix-picker-escape-modal.md
  packages/picker/src/Picker.ts
  packages/picker/stories/picker.stories.ts
  packages/picker/test/index.ts
Labels: bug, ready-for-review

#5665 docs(avatar): update a11y docs
  packages/avatar/README.md
Labels: ready-for-review

#5670 fix(overlay): Programmatic clicks on elements outside of the overlay now registers
  .changeset/fluffy-ads-send.md
  .changeset/solid-points-talk.md
  packages/overlay/README.md
  packages/overlay/src/Overlay.ts
  packages/overlay/test/overlay.test.ts
Labels: bug, ready-for-review, SEV 2

#5669 fix(alert-dialog): added missing imports
  .circleci/config.yml
  packages/alert-dialog/README.md
  packages/alert-dialog/src/AlertDialog.ts
  packages/contextual-help/test/contextual-help.test.ts
Labels: bug, dependencies, needs jira ticket, ready-for-merge, SEV 1

#5707 chore(netlify): remove netlify.toml now that Azure is used for deployments
  netlify.toml
Labels: ready-for-review

#5710 fix(overlay): modal and page overlay should not allow body scroll
  .changeset/grumpy-doors-worry.md
  packages/overlay/src/OverlayStack.ts
  packages/overlay/test/index.ts
Labels: bug, Component: Overlay, Needs Re-review

#5713 bug(slider): remove jsdoc slot deprecation comment in slider
  packages/slider/src/Slider.ts
Labels: bug, ready-for-review
