Repository adobe/spectrum-web-components, pull requests merged in 2025-03, with the labels that each got.

#5137 chore: fix smoke test to run before merge
  .github/workflows/browser-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/test.yml
  .gitignore
  projects/documentation/.gitignore
  projects/documentation/e2e/published.spec.ts
  projects/documentation/package.json
  projects/documentation/scripts/build-search-index.js
  projects/documentation/searchIndex.json
  projects/documentation/src/components/search-index.ts
  test/visual/test.ts
  web-test-runner.config.js
Labels: Testing, ready-for-review

#5085 chore: update field components css dependencies
  .circleci/config.yml
  packages/number-field/package.json
  packages/number-field/src/number-field-overrides.css
  packages/number-field/src/number-field.css
  packages/number-field/src/spectrum-number-field.css
  packages/search/package.json
  packages/search/src/search-overrides.css
  packages/search/src/search.css
  packages/search/src/spectrum-config.js
  packages/search/src/spectrum-search.css
  packages/textfield/package.json
  packages/textfield/src/spectrum-config.js
  packages/textfield/src/spectrum-textfield.css
  packages/textfield/src/textfield-overrides.css
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: Component: Search, Component: Textfield, Component: Number Field, ready-for-review, fast-follow

#4533 build: migrate to changesets from lerna
  .changeset/README.md
  .changeset/config.json
  .github/workflows/beta-release.yml
  .gitignore
  README.md
  RELEASE_PROCESS.md
  commitlint.config.cjs
  lerna.json
  linters/eslint/CHANGELOG.md
  package.json
  projects/story-decorator/decorator.ts
  tasks/confirm-build.js
  tasks/create-git-tag.js
  tasks/custom-element-json.js
  tasks/gen-react-wrapper.js
  tasks/get-changed-packages.js
  tasks/remove-custom-elements-json.js
  tasks/run-check-cem.js
  yarn.lock
Labels: Tooling, ready-for-review

#4957 chore: make vrts stable
  .circleci/config.yml
  packages/overlay/stories/index.ts
  packages/picker/stories/picker.stories.ts
Labels: WIP, Component: Popover, Testing

#5134 chore: update menu css dependencies for fast follows
  .circleci/config.yml
  packages/menu/package.json
  packages/menu/src/menu-item.css
  packages/menu/src/menu-overrides.css
  packages/menu/src/spectrum-checkmark.css
  packages/menu/src/spectrum-chevron.css
  packages/menu/src/spectrum-menu-divider.css
  packages/menu/src/spectrum-menu-item.css
  packages/menu/src/spectrum-menu-sectionHeading.css
  packages/menu/src/spectrum-menu.css
  packages/picker/package.json
  packages/picker/src/spectrum-picker.css
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: ready-for-review, fast-follow

#5124 Accessibility improvements to docs
  packages/action-bar/README.md
  packages/action-button/README.md
  packages/action-menu/README.md
  packages/button-group/README.md
  packages/button/README.md
  packages/card/README.md
  packages/combobox/README.md
  packages/help-text/README.md
  packages/icon/README.md
  packages/icons-ui/README.md
  packages/icons-workflow/README.md
  packages/icons/README.md
  packages/iconset/README.md
  packages/menu/README.md
  packages/menu/menu-group.md
  packages/menu/menu-item.md
  packages/picker-button/README.md
  packages/picker/README.md
  packages/popover/README.md
  packages/slider/README.md
  packages/slider/slider-handle.md
  packages/switch/README.md
  packages/tray/README.md
  projects/documentation/.eleventy.js
  projects/documentation/README.md
  projects/documentation/content/_includes/api.njk
  projects/documentation/content/_includes/changelog.njk
  projects/documentation/content/_includes/component-partial.njk
  projects/documentation/content/_includes/component.njk
  projects/documentation/content/_includes/overview.njk
  projects/documentation/content/_includes/partials/demo.njk
  projects/documentation/content/getting-started.md
  projects/documentation/content/guides/adding-component.md
  projects/documentation/content/shell-start.njk
  projects/documentation/scripts/component-template-parts.js
  projects/documentation/scripts/copy-component-docs.js
  projects/documentation/src/components/layout.ts
  projects/documentation/src/components/styles.css
  projects/documentation/src/router.ts
  projects/documentation/src/utils/posthtml-spectrum-docs-markdown.js
Labels: a11y, Documentation, ready-for-review

#5160 fix(overlay): manual overlay last item should close on pressing escape
  packages/overlay/src/OverlayStack.ts
  packages/overlay/test/overlay-element.test.ts
Labels: bug, Component: Overlay

#5153 fix(picker): S2 corrected border radius and background color
  .circleci/config.yml
  packages/combobox/README.md
  packages/icons/README.md
  packages/picker/package.json
  projects/documentation/.eleventy.js
  storybook/preview.js
  tools/styles/tokens-v2/system-theme-bridge.css
  yarn.lock
Labels: ready-for-review, fast-follow

#5140 feat(contextual-help): allow setting a max-width to popover
  .changeset/bumpy-kids-hug.md
  .circleci/config.yml
  packages/contextual-help/README.md
  packages/contextual-help/package.json
  packages/contextual-help/src/contextual-help-overrides.css
  packages/contextual-help/src/spectrum-contextual-help.css
  packages/contextual-help/stories/contextual-help.stories.ts
  tasks/process-spectrum.js
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: ready-for-review

#5213 docs(picker): force popover documentation and API tab listing fix
  .changeset/witty-words-wish.md
  .circleci/config.yml
  packages/action-menu/README.md
  packages/action-menu/stories/action-menu.stories.ts
  packages/action-menu/stories/index.ts
  packages/picker/README.md
  packages/picker/src/Picker.ts
  packages/picker/stories/picker.stories.ts
Labels: Component: Picker, Documentation, API

#5214 ci: stop dependabot PRs for cutoff
  .github/dependabot.yml
Labels: dependencies, Tooling

#5190 chore: update action button fast follows
  .changeset/clever-bats-walk.md
  .circleci/config.yml
  packages/action-button/package.json
  packages/action-button/src/action-button-overrides.css
  packages/action-button/src/spectrum-action-button.css
  projects/story-decorator/src/StoryDecorator.ts
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: Component: Action Button, ready-for-review, fast-follow

#5212 chore(tabs-overflow): convert scrollContent into a protected getter
  packages/tabs/src/TabsOverflow.ts
Labels: Component: Tabs, ready-for-review

#5241 docs(textfield): updated docs for accessibility
  packages/textfield/README.md
Labels: ready-for-review

#5253 docs(radio-group): split radio-group docs from radio docs
  packages/radio/README.md
  packages/radio/radio-group.md
Labels: ready-for-review

#5252 fix(pickerbutton): picker button version update
  .changeset/dirty-games-prove.md
  packages/picker-button/package.json
  packages/picker-button/src/picker-button-overrides.css
  packages/picker-button/src/spectrum-picker-button.css
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: Spectrum CSS, Component: Picker Button, ready-for-review, do-not-merge, fast-follow

#5248 fix(overlay): stays open when interacting with elements inside
  .changeset/wild-facts-mate.md
  .circleci/config.yml
  packages/overlay/README.md
  packages/overlay/src/Overlay.ts
  packages/overlay/stories/overlay.stories.ts
  packages/overlay/test/overlay.test.ts
Labels: Component: Overlay, ready-for-review

#5187 fix(picker): disable drag and select for mobile picker
  .changeset/bright-brooms-remain.md
  packages/combobox/test/combobox.test.ts
  packages/menu/src/Menu.ts
  packages/menu/test/menu-group.test.ts
  packages/menu/test/menu-selects.test.ts
  packages/menu/test/menu.test.ts
  packages/overlay/src/AbstractOverlay.ts
  packages/overlay/src/OverlayDialog.ts
  packages/overlay/stories/overlay.stories.ts
  packages/picker/src/InteractionController.ts
  packages/picker/src/Picker.ts
  packages/picker/stories/picker.stories.ts
  packages/picker/test/index.ts
Labels: bug, Component: Menu, ready-for-review

#5234 chore: add build command to renovate
  renovate.json
Labels: Tooling, ready-for-review

#5151 chore: remove local stylelint-header for published version
  .stylelintrc.json
  linters/stylelint-header/CHANGELOG.md
  linters/stylelint-header/README.md
  linters/stylelint-header/index.js
  linters/stylelint-header/package.json
  linters/stylelint-header/test/fail.css
  linters/stylelint-header/test/fixed.css
  linters/stylelint-header/test/input.txt
  linters/stylelint-header/test/pass.css
  linters/stylelint-header/test/stylelint-header.test.js
  package.json
  packages/breadcrumbs/src/breadcrumbs.css
  packages/color-area/src/color-area.css
  packages/color-slider/src/color-slider.css
  packages/textfield/src/textfield.css
  yarn.lock
Labels: enhancement, dependencies, ready-for-review

#5278 chore: resolve allowed commands error for renovate tool
  renovate.json
Labels: dependencies, Tooling, ready-for-review

#5016 build: remove the build task from postinstall
  .circleci/config.yml
  .github/actions/setup-job/action.yml
  RELEASE_PROCESS.md
  package.json
  yarn.lock
Labels: enhancement, Tooling, ready-for-review

#5268 chore: updated genversion script to update version.js file before publish
  package.json
  tasks/update-version.js
Labels: Tooling

#5262 chore: updated chromedriver for tachometer tests
  .github/workflows/browser-tests.yml
  package.json
  tasks/get-changed-packages.js
  yarn.lock
Labels: Tooling

#5202 chore(combobox): s2 fast follows fix
  .changeset/dirty-games-prove.md
  .changeset/odd-cloths-start.md
  .circleci/config.yml
  packages/combobox/package.json
  packages/combobox/src/combobox-overrides.css
  packages/combobox/src/combobox.css
  packages/combobox/src/spectrum-combobox.css
  packages/picker-button/package.json
  packages/picker-button/src/picker-button-overrides.css
  packages/picker-button/src/spectrum-picker-button.css
  packages/textfield/package.json
  packages/textfield/src/spectrum-textfield.css
  packages/textfield/src/textfield-overrides.css
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: Component: Combobox, Spectrum CSS, ready-for-review, fast-follow
