Repository adobe/spectrum-web-components, pull requests merged in 2025-09, with the labels that each got.

#5716 docs(dropzone): dropzone doc audit
  packages/dropzone/README.md
Labels: Documentation, ready-for-review

#5744 chore(deps): pin package dependencies [SWC-1243]
  package.json
  packages/action-group/package.json
  packages/alert-dialog/package.json
  packages/icons-ui/package.json
  packages/icons-workflow/package.json
  packages/menu/package.json
  packages/number-field/package.json
  packages/overlay/package.json
  packages/slider/package.json
  packages/swatch/package.json
  packages/table/package.json
  packages/tabs/package.json
  packages/top-nav/package.json
  projects/css-custom-vars-viewer/package.json
  projects/documentation/package.json
  projects/example-project-rollup/package.json
  projects/example-project-webpack/package.json
  projects/templates/package.json
  tools/grid/package.json
  tools/reactive-controllers/package.json
  tools/shared/package.json
  yarn.lock
Labels: dependencies, Priority, ready-for-review, skip_lint

#5747 fix(sp-alert-dialog): Make the divider color transparent for S2 theme
  .changeset/eight-parts-begin.md
  .circleci/config.yml
  packages/alert-dialog/src/alert-dialog-overrides.css
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
Labels: Component: Alert Dialog, ready-for-merge

#5733 fix(sp-picker): s2 theme update - no borders for picker
  .changeset/honest-words-say.md
  .circleci/config.yml
  tools/styles/tokens-v2/system-theme-bridge.css
Labels: Component: Picker, ready-for-merge
