Repository adobe/spectrum-web-components, pull requests merged in 2025-04, with the labels that each got.

#5308 fix(overlay): prevent overlay close on document scroll
  .changeset/giant-moles-divide.md
  packages/overlay/src/OverlayStack.ts
  packages/picker/test/index.ts
Labels: bug, Component: Picker, ready-for-review

#5310 chore: align and update changesets
  .changeset/brave-crews-win.md
  .changeset/cool-emus-appear.md
  .changeset/cute-peas-chew.md
  .changeset/good-lizards-brake.md
  .changeset/itchy-dots-draw.md
  .changeset/lazy-rivers-camp.md
  .changeset/public-steaks-juggle.md
  .changeset/sharp-dodos-start.md
  .changeset/tidy-oranges-agree.md
  .changeset/warm-ducks-dig.md
Labels: Tooling, ready-for-review

#5313 fix(menu): capture touchend on mobile
  .changeset/spicy-ants-travel.md
  packages/menu/src/Menu.ts
  packages/menu/stories/menu-item.stories.ts
Labels: ready-for-review

#5224 chore: update tachometer reporting to stabilize ci [SWC-767]
  .github/workflows/browser-tests.yml
Labels: Tooling, ready-for-review, github_actions

#5270 fix(menu): menuitem focus and hover styles
  .changeset/spicy-papers-fold.md
  .circleci/config.yml
  packages/menu/src/Menu.ts
  packages/menu/src/MenuItem.ts
  packages/menu/test/menu.test.ts
  packages/menu/test/submenu.test.ts
  test/testing-helpers.ts
  tools/reactive-controllers/src/FocusGroup.ts
Labels: ready-for-review

#5350 fix(menu): larger than margin in menu-item
  .changeset/better-glasses-burn.md
  .circleci/config.yml
  packages/menu/src/menu-group.css
  packages/menu/src/menu.css
Labels: Component: Menu, ready-for-review

#5363 fix(button): hoisted modifier access
  .changeset/curvy-boxes-poke.md
  .circleci/config.yml
  packages/button/package.json
  packages/button/src/button-overrides.css
  packages/button/src/spectrum-button.css
  tools/styles/tokens-v2/system-theme-bridge.css
  tools/styles/tokens/express/system-theme-bridge.css
  tools/styles/tokens/spectrum/system-theme-bridge.css
  yarn.lock
Labels: bug, Component: Button, Spectrum CSS, ready-for-review

#5364 docs: field-label accessibility docs
  packages/field-label/README.md
Labels: a11y, ready-for-review

#5323 fix(tabs): ensure tabs become enabled when parent disabled attribute is removed
  .changeset/twenty-ads-shake.md
  packages/tabs/src/Tabs.ts
  packages/tabs/test/tabs.test.ts
Labels: Component: Tabs, Contribution, ready-for-review

#5376 fix: tachometer results file path for performance comments
  .changeset/metal-baths-stand.md
  tasks/build-tachometer-comment.js
Labels: on hold

#5174 chore(button): S2 fast follows fixes
  .changeset/olive-maps-accept.md
  .circleci/config.yml
  packages/button/CHANGELOG.md
  packages/button/README.md
  packages/button/src/Button.ts
  packages/button/stories/button-black-fill.stories.ts
  packages/button/stories/button-black-outline.stories.ts
  packages/button/stories/button-white-fill.stories.ts
  packages/button/stories/button-white-outline.stories.ts
  packages/button/stories/index.ts
  packages/button/stories/template.ts
  packages/button/test/button.test.ts
  yarn.config.cjs
Labels: ready-for-review, fast-follow

#5367 fix(icons): added missing workflow icons
  .changeset/eight-ravens-admire.md
  .circleci/config.yml
  packages/icons-workflow/bin/icons-mapping.json
  packages/icons-workflow/package.json
  packages/iconset/stories/iconsList.json
  yarn.lock
Labels: ready-for-review

#5381 docs(checkbox): updated checkbox documentation for accessbility
  packages/checkbox/README.md
Labels: ready-for-review

#5388 chore: correct package name in changeset
  .changeset/stale-candies-camp.md
Labels: bug, ready-for-review

#5358 fix(picker): menuitem focus when opened via mouse
  .changeset/fluffy-sides-cross.md
  packages/action-group/test/action-group.test.ts
  packages/picker/src/Picker.ts
  packages/picker/test/index.ts
Labels: ready-for-review

#5384 chore: added story to demonstrate a delayed tooltip example
  .changeset/slimy-terms-hang.md
  .circleci/config.yml
  packages/tooltip/stories/tooltip.stories.ts
Labels: ready-for-review

#5408 fix(number-field): sp-number-field UI fixes for validation and width
  .changeset/silly-rooms-talk.md
  .circleci/config.yml
  packages/number-field/README.md
  packages/number-field/src/number-field.css
  packages/number-field/stories/number-field.stories.ts
Labels: Component: Number Field, ready-for-review
