Repository adobe/spectrum-web-components, pull requests merged in 2025-06, with the labels that each got.

#5501 docs(status-light): updated for accessbility
  packages/status-light/README.md
Labels: ready-for-review

#5504 fix(tooltip,textfield,sidenav): update deprecated css [CSS-1223]
  .changeset/word-break-updates.md
  packages/sidenav/src/spectrum-sidenav-item.css
  packages/textfield/src/textfield.css
  packages/tooltip/src/spectrum-tooltip.css
Labels: bug, Component: Tooltip, Component: Textfield, Components: Side Navigation, Spectrum CSS, jira ticket created, auto-update, ready-for-merge

#5328 ci: global changelog generator script
  .changeset/rich-bears-fold.md
  CHANGELOG.md
  package.json
  scripts/update-global-changelog.js
Labels: Priority, Tooling, ready-for-review

#5507 chore: migrate linting from circleci to github actions
  .circleci/config.yml
  .eslintrc.json
  .github/workflows/lint.yml
  .gitignore
  .stylelintrc.json
  package.json
  yarn.lock
Labels: Tooling, ready-for-review

#5530 chore: checkout before fetching changed files to have a baseline to run against
  .github/workflows/lint.yml
Labels: Tooling, ready-for-review

#5524 fix(switch): down state styles take precedence over hover
  .changeset/grumpy-forks-bathe.md
  packages/switch/src/switch.css
Labels: Component: Switch, Spectrum CSS Bug, Visual Bug, ready-for-merge

#5529 fix(styles): cjk alias mapping fixed
  .changeset/fair-carrots-kiss.md
  tools/styles/tokens-v2/global-vars.css
  tools/styles/tokens-v2/index.css
  tools/styles/tokens-v2/spectrum/custom-vars.css
  tools/styles/tokens/index.css
  tools/styles/tokens/spectrum/custom-vars.css
  tools/styles/tokens/spectrum/global-vars.css
  tools/styles/tokens/spectrum/index.css
Labels: Spectrum CSS, ready-for-review
