Repository adobe/spectrum-web-components, pull requests merged in 2025-05, with the labels that each got.

#5418 chore(underlay): updates docs
  packages/underlay/README.md
Labels: ready-for-review, Component: Underlay

#5425 chore: add 1.6.0 changelog notes
  CHANGELOG.md
Labels: ready-for-review

#5387 docs: improve contributing and pull request documentation
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/azure-static-web-apps-brave-plant-02f0c200f.yml
  CONTRIBUTING.md
  PULL_REQUESTS.md
Labels: Documentation, ready-for-review

#5403 chore: storybook decorator fixed height for overlay stories
  projects/story-decorator/decorator.ts
  storybook/preview-head.html
Labels: ready-for-review

#5409 docs(overlay): a11y docs update
  packages/overlay/README.md
  packages/overlay/imperative-api.md
  packages/overlay/overlay-trigger.md
  packages/overlay/slottable-request.md
  packages/overlay/src/Overlay.ts
  packages/overlay/src/OverlayTrigger.ts
  packages/overlay/trigger-directive.md
Labels: ready-for-review

#5411 docs(dialog): updated dialog docs for accessbility
  packages/dialog/README.md
  packages/dialog/dialog-base.md
  packages/dialog/dialog-wrapper.md
  projects/documentation/content/guides/adding-component.md
  projects/documentation/scripts/build-search-index.js
Labels: Component: Dialog, ready-for-review

#5440 docs: added writing changeset docs
  .changeset/README.md
  README.md
  projects/documentation/content/guides/writing-changesets.md
Labels: ready-for-review, auto-update

#5445 chore: missed workflow trigger
  .github/workflows/pr-update.yml
Labels: Tooling, ready-for-review

#5441 docs(toast): updated toast docs for accessibility
  packages/toast/README.md
Labels: Component: Toast, ready-for-review, auto-update

#5443 chore: clean-up duplicate dependency manager
  .github/dependabot.yml
  .github/renovate.json
  renovate.json
Labels: ready-for-review

#5449 fix(card): added missing sp-popover dependency
  .changeset/cuddly-lands-work.md
  packages/card/package.json
  yarn.lock
Labels: dependencies, ready-for-merge

#5432 fix: skip elements with focusable="false" attribute
  tools/shared/src/focusable-selectors.ts
Labels: ready-for-review

#5477 fix(overlay): scroll jitter due to layout thrashing in safari and safari
  .changeset/happy-cycles-check.md
  packages/overlay/src/OverlayStack.ts
  packages/picker/test/index.ts
Labels: bug, Component: Overlay, Component: Action Menu, ready-for-review

#5478 chore: update version alignment tooling [SWC-898]
  .github/workflows/preview-release.yml
  README.md
  package.json
  packages/icons-ui/package.json
  packages/icons-workflow/package.json
  projects/example-project-rollup/package.json
  scripts/lint-versions.js
  tasks/update-version.js
  tools/base/package.json
  tools/bundle/package.json
  tools/grid/package.json
  tools/opacity-checkerboard/package.json
  tools/reactive-controllers/package.json
  tools/shared/package.json
  tools/styles/package.json
  tools/theme/package.json
  tools/truncated/package.json
  yarn.config.cjs
  yarn.lock
Labels: Tooling, ready-for-review

#5466 docs(progress-circle): a11y audit
  packages/progress-circle/README.md
Labels: ready-for-review, ready-for-merge

#5468 docs(coachmark): a11y audit
  packages/coachmark/README.md
  packages/coachmark/coach-indicator.md
Labels: ready-for-review, ready-for-merge
