Repository adobe/spectrum-web-components, pull requests merged in 2025-07, with the labels that each got.

#5171 fix(card): card component checkbox accessibility name and keyboard access #5168
  .changeset/thick-keys-tickle.md
  .circleci/config.yml
  packages/action-menu/test/index.ts
  packages/card/README.md
  packages/card/src/Card.ts
  packages/card/src/card.css
  packages/card/stories/card.stories.ts
  packages/card/test/card.test.ts
  tools/grid/README.md
  tools/grid/src/Grid.ts
  tools/grid/stories/grid.stories.ts
  tools/grid/test/grid.test.ts
Labels: Priority, Component: Card, a11y, ready-for-review

#5505 chore: cursor utilities [CSS-1222]
  .cursor/README.md
  .cursor/config.json
  .cursor/rules/branch-naming.mdc
  .cursor/rules/jira-ticket.mdc
  .cursor/rules/styles.mdc
  .cursor/rules/text-formatting.mdc
Labels: Tooling, ready-for-review, jira ticket created, auto-update

#5592 docs(accordion): updated accordion and accordion-item docs for accessibility
  packages/accordion/README.md
  packages/accordion/accordion-item.md
Labels: ready-for-review

#5597 chore: improve cursor jira prompts
  .cursor/rules/github-description.mdc
  .cursor/rules/jira-ticket.mdc
Labels: Tooling, Documentation, ready-for-review, SEV 5

#5576 fix(typography): unintended typography element margins
  tools/styles/fonts.css
  tools/styles/src/spectrum-detail.css
  tools/styles/src/spectrum-heading.css
  tools/styles/typography.css
Labels: ready-for-merge

#5553 docs(progress-bar): documentation updates
  .changeset/easy-jobs-brush.md
  packages/.eslintrc.json
  packages/progress-bar/README.md
  packages/progress-bar/package.json
  packages/progress-bar/src/ProgressBar.ts
  packages/progress-bar/test/progress-bar.test.ts
  tools/.eslintrc.json
Labels: Documentation, ready-for-review, blocked, ready-for-merge

#5571 docs(tabs): update a11y docs
  packages/tabs/README.md
Labels: Documentation, ready-for-review, blocked, ready-for-merge

#5621 docs(tabs-overflow): update a11y docs
  packages/tabs/tabs-overflow.md
Labels: enhancement, Documentation, ready-for-review

#5634 fix(overlay-testing-helpers): resolve race condition that lead to flaky test results
  packages/overlay/test/overlay-testing-helpers.ts
  packages/overlay/test/overlay-trigger-extended.test.ts
Labels: ready-for-review

#5636 chore: disable flaky number field test in webkit
  packages/number-field/test/number-field.test.ts
Labels: Testing, Component: Number Field, ready-for-review

#5637 chore: skipping flaky overlay tests
  packages/overlay/test/overlay-trigger-extended.test.ts
  packages/picker/test/index.ts
Labels: Component: Overlay, Testing, ready-for-review

#5617 test(number-field): ensure element updates after input events
  packages/number-field/test/number-field.test.ts
Labels: Testing, ready-for-review

#5640 docs(color-wheel): enhance README
  packages/color-wheel/README.md
Labels: ready-for-review

#5635 docs(badge): audit and update accessibility documentation
  packages/badge/README.md
Labels: Documentation, Components: Badge, ready-for-review
