Repository adobe/spectrum-web-components, pull requests merged in 2025-02, with the labels that each got.

#5063 build: fix chromatic build workflow github actions
  .github/workflows/chromatic-vrt.yml
Labels: bug, ready-for-review, github_actions

#5088 fix(picker): update picker when menu item icons change
  .circleci/config.yml
  packages/menu/src/MenuItem.ts
  packages/picker/stories/picker.stories.ts
  packages/picker/test/index.ts
Labels: Component: Picker

#5104 feat(combobox): allow support for disabled items
  packages/combobox/README.md
  packages/combobox/src/Combobox.ts
  packages/combobox/stories/combobox.stories.ts
  packages/combobox/stories/index.ts
  packages/combobox/test/combobox.test.ts
  packages/combobox/test/helpers.ts
Labels: ready-for-review

#5102 fix(icons): added spectrum 1 missing icons
  .circleci/config.yml
  packages/icons-workflow/package.json
  packages/iconset/stories/iconsList.json
  yarn.lock
Labels: ready-for-review

#5100 fix(breadcrumbs): show maxvisibleitems on dynamic updates
  packages/breadcrumbs/src/Breadcrumbs.ts
  packages/breadcrumbs/stories/args.ts
  packages/breadcrumbs/stories/breadcrumbs.stories.ts
  packages/breadcrumbs/test/breadcrumbs.test.ts
  projects/documentation/content/_includes/partials/demo.njk
  projects/documentation/src/components/demo-container.css
  projects/documentation/src/components/styles.css
Labels: ready-for-review

#5031 fix(action menu): keyboard accessibility omnibus
  .changeset/lemon-points-ring.md
  .circleci/config.yml
  packages/action-group/src/ActionGroup.ts
  packages/action-group/test/action-group.test.ts
  packages/action-menu/src/ActionMenu.ts
  packages/action-menu/stories/action-menu.stories.ts
  packages/action-menu/test/action-menu-directive.test.ts
  packages/action-menu/test/action-menu-groups.test.ts
  packages/action-menu/test/index.ts
  packages/combobox/src/Combobox.ts
  packages/combobox/test/combobox-a11y.test.ts
  packages/combobox/test/combobox.test.ts
  packages/combobox/test/helpers.ts
  packages/menu/menu-group.md
  packages/menu/menu-item.md
  packages/menu/src/Menu.ts
  packages/menu/src/MenuGroup.ts
  packages/menu/src/MenuItem.ts
  packages/menu/stories/index.ts
  packages/menu/stories/menu.stories.ts
  packages/menu/test/menu-group.test.ts
  packages/menu/test/menu-item.test.ts
  packages/menu/test/menu-selects.test.ts
  packages/menu/test/menu.test.ts
  packages/menu/test/submenu.test.ts
  packages/overlay/stories/overlay.stories.ts
  packages/picker/src/InteractionController.ts
  packages/picker/src/MobileController.ts
  packages/picker/src/Picker.ts
  packages/picker/test/index.ts
  packages/picker/test/picker-reparenting.test.ts
  packages/tabs/test/tabs.test.ts
  tools/reactive-controllers/src/FocusGroup.ts
  tools/reactive-controllers/src/RovingTabindex.ts
  tools/reactive-controllers/test/roving-tabindex-integration.test.ts
Labels: ready-for-review
